const MAX_DEGREE = 359.9;
const RADIUS = 80;
const STROKE_WIDTH = 18;
const SIZE = 200;
const POS = SIZE / 2;
const VIEW_BOX = `0 0 ${SIZE} ${SIZE}`;

// 모바일(태블릿)용 사이즈
const RADIUS_SMALL = 50;
const SIZE_SMALL = 140;
const STROKE_WIDTH_SMALL = 12;
const POS_SMALL = SIZE_SMALL / 2;
const VIEW_BOX_SMALL = `0 0 ${SIZE_SMALL} ${SIZE_SMALL}`;


export { MAX_DEGREE, RADIUS, STROKE_WIDTH, SIZE, POS, VIEW_BOX, RADIUS_SMALL, SIZE_SMALL, STROKE_WIDTH_SMALL, POS_SMALL, VIEW_BOX_SMALL };
